version: '3.9'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    # volumes:
    #   - postgres-data:/var/lib/postgresql/data

    #   api:
    #     build: .
    #     ports:
    #       - "3031:3031"
    #     depends_on:
    #       - db
    #     environment:
    #       DATABASE_URL: postgres://postgres:password@db:5432/users

    # volumes:
    #   postgres-data:
