version: '3.9'

services:
  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "AdminPassword1"
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433
  # Uncomment the API section if needed
  # api:
  #   build: .
  #   ports:
  #     - "3031:3031"
  #   depends_on:
  #     - db
  #   environment:
  #     DATABASE_URL: mssql://sa:AdminPassword1@db:1433/forget_me_notes

  # Uncomment if you want persistent data
  # volumes:
  #   mssql-data:

